apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: flow-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: simulation-source
    properties:
      message: 'Nicola Ferraro'
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
