apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: insert-field
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "Insert Field"
    description: "Adds a custom field with a constant value to the message"
    required:
      - field
      - value
    properties:
      field:
        title: Field
        description: The name of the field to be added
        type: string
      value:
        title: Value
        description: The value of the field
        type: string
  dependencies:
  - github:nicolaferraro:kamelet-message-transformation:main-SNAPSHOT
  flow:
    from:
      uri: kamelet:source
      steps:
        - unmarshal:
            json: {}
        - set-property:
            name: "field"
            constant: "{{field}}"
        - set-property:
            name: "value"
            constant: "{{value}}"
        - bean: "com.github.nicolaferraro.kamelets.InsertField"
        - marshal:
            json: {}
