apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: log-sink
  annotations:
    camel.apache.org/provider: "Apache Software Foundation"
  labels:
    camel.apache.org/kamelet.type: sink
spec:
  definition:
    title: Log Sink
    description: Displays detailed information about incoming events.
  flow:
    from:
      uri: kamelet:source
      steps:
        - to: log:info?showAll=true
